In [1]:
import pandas as pd

In [6]:
df = pd.read_csv("/content/AdultIncome.csv")

In [7]:
df

       age        wc      education  ...   gender hours per week IncomeClass
0       38   Private        HS-grad  ...     Male             40       <=50K
1       28   Private      Bachelors  ...   Female             40       <=50K
2       37   Private        Masters  ...   Female             40       <=50K
3       31   Private        Masters  ...   Female             50        >50K
4       42   Private      Bachelors  ...     Male             40        >50K
...    ...       ...            ...  ...      ...            ...         ...
19782   53   Private        Masters  ...     Male             40        >50K
19783   22   Private   Some-college  ...     Male             40       <=50K
19784   40   Private        HS-grad  ...     Male             40        >50K
19785   58   Private        HS-grad  ...   Female             40       <=50K
19786   22   Private        HS-grad  ...     Male             20       <=50K

[19787 rows x 8 columns]

In [4]:
df = pd.get_dummies(df)

In [5]:
df

       age  hours per week  ...  IncomeClass_ <=50K  IncomeClass_ >50K
0       38              40  ...                   1                  0
1       28              40  ...                   1                  0
2       37              40  ...                   1                  0
3       31              50  ...                   0                  1
4       42              40  ...                   0                  1
...    ...             ...  ...                 ...                ...
19782   53              40  ...                   0                  1
19783   22              40  ...                   1                  0
19784   40              40  ...                   0                  1
19785   58              40  ...                   1                  0
19786   22              20  ...                   1                  0

[19787 rows x 26 columns]

In [8]:
df = pd.get_dummies(df, drop_first=True)

In [9]:
df

       age  hours per week  ...  gender_ Male  IncomeClass_ >50K
0       38              40  ...             1                  0
1       28              40  ...             0                  0
2       37              40  ...             0                  0
3       31              50  ...             0                  1
4       42              40  ...             1                  1
...    ...             ...  ...           ...                ...
19782   53              40  ...             1                  1
19783   22              40  ...             1                  0
19784   40              40  ...             1                  1
19785   58              40  ...             0                  0
19786   22              20  ...             1                  0

[19787 rows x 20 columns]

In [10]:
x = df.iloc[:,:-1].values

In [11]:
y = df.iloc[:,-1].values

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [13]:
from sklearn.tree import DecisionTreeClassifier

In [14]:
dtc = DecisionTreeClassifier(random_state=0)

In [15]:
dtc.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [16]:
y_pred = dtc.predict(x_test)

In [18]:
y_test

array([0, 1, 1, ..., 0, 0, 0], dtype=uint8)

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [20]:
confusion_matrix(y_test, y_pred)

array([[2525,  353],
       [ 510,  570]])

In [21]:
accuracy_score(y_test, y_pred)

0.7819605861546235